version: "2"

linters:
  default: none
  enable:
    - loglint

  settings:
    custom:
      loglint:
        type: "module"
        description: "Проверка log-сообщений: строчные буквы, только английский, спецсимволы/эмодзи, чувствительные данные"
        settings: {}
